version: "3.9"

services:
  wp-mysql:
    container_name: wp-mysql
    image: mysql:latest
    restart: always

    cap_add:
      - SYS_NICE

    volumes:
      - wp-mysql-data:/var/lib/mysql

    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD

  wp-nginx:
    container_name: wp-nginx
    image: nginx:stable-alpine
    depends_on:
      - wp-php
      - wp-mysql

    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./wordpress:/var/www/html

    ports:
      - 80:80
      - 443:443

  wp-php:
    container_name: wp-php
    build:
      context: .
      dockerfile: php.dockerfile

    volumes:
      - ./wordpress:/var/www/html

volumes:
  wp-mysql-data:
